Smooth Watermelon Urchin

Medium

# `DebitaChainlink:checkSequencer` does not validate an invalid update round status of the sequencer uptime feed.

### Summary

`checkSequencer` function doesn’t validate the status of the sequencer, if there is some problem with the sequencer then the startedAt will be 0, because of this the grace period check will always pass even if there is some problem with sequencer. 

### Root Cause

The DebitaChainlink contract has a check to ensure the sequencer uptime in [checkSequencer](https://github.com/sherlock-audit/2024-11-debita-finance-v3/blob/376fec45be95bd4bbc929fd37b485076b03ab8b0/Debita-V3-Contracts/contracts/oracles/DebitaChainlink.sol#L49) function.

```js
function checkSequencer() public view returns (bool) {
        (, int256 answer, uint256 startedAt, , ) = sequencerUptimeFeed
            .latestRoundData();

        // Answer == 0: Sequencer is up
        // Answer == 1: Sequencer is down
        bool isSequencerUp = answer == 0;
        if (!isSequencerUp) {
            revert SequencerDown();
        }
        console.logUint(startedAt);
        // Make sure the grace period has passed after the
        // sequencer is back up.
        uint256 timeSinceUp = block.timestamp - startedAt;
        if (timeSinceUp <= GRACE_PERIOD_TIME) {
            revert GracePeriodNotOver();
        }

        return true;
    }

```

The checks here is not implemented correctly. The [chainlink docs](https://docs.chain.link/data-feeds/l2-sequencer-feeds) say that sequencerUptimeFeed can return a 0 value for `startedAt` if it is called during an “invalid round”.


> **startedAt:** This timestamp indicates when the sequencer changed status. This timestamp returns 0 if a round is invalid. When the sequencer comes back up after an outage, wait for the `GRACE_PERIOD_TIME` to pass before accepting answers from the data feed. Subtract startedAt from block.timestamp and revert the request if the result is less than the `GRACE_PERIOD_TIME`.
> 
> 
> If the sequencer is up and the `GRACE_PERIOD_TIME` has passed, the function retrieves the latest answer from the data feed using the `dataFeed` object.
> 

Please note that an “invalid round” is described to mean there was a problem updating the sequencer’s status, possibly due to network issues or problems with data from oracles, and is shown by a `startedAt` time of 0 and `answer` is 0. 

This makes the implemented check below in the [DebitaChainlink](https://github.com/sherlock-audit/2024-11-debita-finance-v3/blob/376fec45be95bd4bbc929fd37b485076b03ab8b0/Debita-V3-Contracts/contracts/oracles/DebitaChainlink.sol#L62C8-L65C10)  to be useless if its called in an invalid round.

```jsx
  uint256 timeSinceUp = block.timestamp - startedAt;
        if (timeSinceUp <= GRACE_PERIOD_TIME) {
            revert GracePeriodNotOver();
        }
```

As `startedAt` will be 0, the arithmetic operation `block.timestamp - startedAt` will result in a value greater than `GRACE_PERIOD_TIME` (which is hardcoded to be 3600 seconds). I.e., `block.timestamp = 1719739032`, so 1719739032 - 0 = 1719739032 which is bigger than 3600. The code won’t revert.

From these explanations and information, it can be seen that `startedAt` value is a second value that should be used in the check for if a sequencer is down/up or correctly updated. The checks in `DebitaChainlink:checkSequencer` will allow for successfull calls in an invalid round because reverts don’t happen if `answer == 0` and `startedAt == 0` thus defeating the purpose of having a `sequencerFeed` check to ascertain the status of the `sequencerFeed` on L2 (i.e., if it is up/down/active or if its status is actually confirmed to be either).

### Internal pre-conditions

There is not check on `startedAt` variable returned from chainlink.

### External pre-conditions

In case if there is some issue with sequencer, the `startedAt` will be 0.

### Attack Path

_No response_

### Impact

Inadequate checks to confirm the correct status of the sequencer/`sequencerUptimeFeed` in `DebitaChainlink:checkSequencer` will cause `getThePrice()` to not revert even when the sequencer uptime feed is not updated or is called in an invalid round.

The same issue was found in [[size contest in c4](https://code4rena.com/reports/2024-06-size#m-04-inadequate-checks-to-confirm-the-correct-status-of-the-sequencesequenceruptimefeed-in-pricefeedgetprice-contract)](https://code4rena.com/reports/2024-06-size#m-04-inadequate-checks-to-confirm-the-correct-status-of-the-sequencesequenceruptimefeed-in-pricefeedgetprice-contract) , please have a look if something is not clear.

### PoC

_No response_

### Mitigation

Add a check that reverts if startedAt is returned as 0. 