Magic Vinyl Aardvark

High

# `DebitaPyth::getThePrice` incorrectly integrates  getPriceNoOlderThan

### Summary

[Pyth documentation](https://docs.pyth.network/price-feeds/use-real-time-data/evm) directly says to call updatePriceFeeds before calling getPriceNoOlderThan.
```solidity
// Submit a priceUpdate to the Pyth contract to update the on-chain price.
    // Updating the price requires paying the fee returned by getUpdateFee.
    // WARNING: These lines are required to ensure the getPriceNoOlderThan call below succeeds. If you remove them, transactions may fail with "0x19abf40e" error.
    uint fee = pyth.getUpdateFee(priceUpdate);
    pyth.updatePriceFeeds{ value: fee }(priceUpdate);
```
Otherwise the transaction may crash with 0x19abf40e error. The protocol does not catch this error when calling [getPriceNoOlderThan](https://github.com/sherlock-audit/2024-11-debita-finance-v3/blob/main/Debita-V3-Contracts/contracts/oracles/DebitaPyth.sol#L25), although it does not call updatePriceFeeds. Thus, the function may terminate with revert and become a point of failure for all other protocol functions calling it.

```solidity
function getThePrice(address tokenAddress) public view returns (int) {
        // falta hacer un chequeo para las l2
        bytes32 _priceFeed = priceIdPerToken[tokenAddress];
        require(_priceFeed != bytes32(0), "Price feed not set");
        require(!isPaused, "Contract is paused");

        // Get the price from the pyth contract, no older than 90 seconds
        PythStructs.Price memory priceData = pyth.getPriceNoOlderThan(
            _priceFeed,
            600
        );

        // Check if the price feed is available and the price is valid
        require(isFeedAvailable[_priceFeed], "Price feed not available");
        require(priceData.price > 0, "Invalid price");
        return priceData.price;
    }
```
### Root Cause

The protocol does not call updatePriceFeeds before calling getPriceNoOlderThan, which allows for the possibility that the call will end with revert due to error 0x19abf40e.

However, the protocol does not catch this error either.

### Internal pre-conditions

_No response_

### External pre-conditions

The price has not been updated for the specified time (for this function it is 600 seconds). In this case - the call will end with revert

### Attack Path

_No response_

### Impact

Incorrect integration can create a single point of failure. The protocol simply stops supporting all calls that cause to this price feed, so matchOffers in the Aggregator will not work for all offers that use pyth oracle for this token.


### PoC

_No response_

### Mitigation

Call updatePriceFeeds before getPriceNoOlderThan