Creamy Opal Rabbit

High

# Insufficient check for chainlink `isSequencerUp` can cause borrows to be filled with invalid price

### Summary

Per the audit README,

> **On what chains are the smart contracts going to be deployed?**
> Sonic (Prev. Fantom), Base, Arbitrum & OP

The PriceFeed contract has sequencerUptimeFeed checks in place to assert if the sequencer on an L2 is running but these checks are not implemented correctly. The [chainlink docs ](https://docs.chain.link/data-feeds/l2-sequencer-feeds)say that sequencerUptimeFeed can return a 0 value for `startedAt` if "the Sequencer Uptime contract is not yet initialized".

> **`startedAt`**: This timestamp indicates when the sequencer feed changed status. When the sequencer comes back up after an outage, wait for the GRACE_PERIOD_TIME to pass before accepting answers from the data feed. ....
> ...The `startedAt` variable returns 0 only on Arbitrum when the Sequencer Uptime contract is not yet initialized.

This can be possibly due to network issues or problems with data from oracles, and is shown by a `startedAt` time of 0 and `answer` is 0. Further explanation can be seen as given by an official chainlink engineer as seen [here](https://discord.com/channels/592041321326182401/605768708266131456/1213847312141525002) in the chainlink public discord


<img width="726" alt="Screenshot 2024-11-25 at 14 28 00" src="https://github.com/user-attachments/assets/a514dec2-5691-47cf-9edc-f9350f72a238">

This makes the implemented check below in the [`checkSequencer()`](https://github.com/sherlock-audit/2024-11-debita-finance-v3/blob/main/Debita-V3-Contracts/contracts/oracles/DebitaChainlink.sol#L55-L65) to be useless if its called when the uptime feed contract has not been initialised.

```solidity
File: DebitaChainlink.sol
49:     function checkSequencer() public view returns (bool) {
50:         (, int256 answer, uint256 startedAt, , ) = sequencerUptimeFeed // @audit something about this from size lending
51:             .latestRoundData();
52: 
53:         // Answer == 0: Sequencer is up
54:         // Answer == 1: Sequencer is down
55:  @>     bool isSequencerUp = answer == 0;
56:  @>     if (!isSequencerUp) {
57:             revert SequencerDown();
58:         }
59:         console.logUint(startedAt);
60:         // Make sure the grace period has passed after the
61:         // sequencer is back up.
62:         uint256 timeSinceUp = block.timestamp - startedAt;
63:  @>     if (timeSinceUp <= GRACE_PERIOD_TIME) {
64:             revert GracePeriodNotOver();
65:         }

```


as `startedAt` will be 0, the arithmetic operation `block.timestamp - startedAt` will result in a value greater than `GRACE_PERIOD_TIME` (which is hardcoded to be `1 hours` or 3600) i.e 
```solidity
block.timestamp = 1732544440, so 1732544440 - 0 = 1732544440 
```
which is bigger than 3600. The code will not revert.

Imagine a case where a round starts, at the beginning `startedAt` is still 0, and `answer` the initial status is set to be 0. Note that docs say that if answer = 0, sequencer is up, if equals to 1, sequencer is down. But in this case here, answer and `startedAt` can be 0 initially, till after all data is gotten from oracles and update is confirmed then the values are reset to the correct values that show the **correct status of the sequencer**.

From these explanations and information, it can be seen that `startedAt` value is a second value that should be used in the check for if a sequencer is down/up or correctly updated. The checks in [`getThePrice()`](https://github.com/sherlock-audit/2024-11-debita-finance-v3/blob/main/Debita-V3-Contracts/contracts/oracles/DebitaChainlink.sol#L39-L41) will allow for successful calls  possibly returning answers from an invalid round because reverts don't happen if answer == 0 and startedAt == 0 (at the same time) thus defeating the purpose of having a sequencerFeed check to ascertain the status of the sequencerFeed on Arbitrum i.e if it is up/down/active or if its status is actually confirmed to be either.

### Root Cause

_No response_

### Internal pre-conditions

_No response_

### External pre-conditions

Chainlink sequencer uptime contract has not been initialised on Arbitrum

### Attack Path

_No response_

### Impact

inadequate checks to confirm the correct status of the sequecncer/sequecncerUptimeFeed in `DebitaChainlink` contract will cause `getThePrice()` to not revert even when the sequcncer uptime feed is not updated or is called in an invalid round.


From the audit README
> In the event that the sequencer is down, no additional loans should be created immediately with Chainlink Oracles. 

This means borrows will succeed even in this condition 
- with  invalid prices
- and thus breaking core protocol invariant

### PoC

_No response_

### Mitigation

Modify the `checkSequencer()` function as shown below

```diff
File: DebitaChainlink.sol
49:     function checkSequencer() public view returns (bool) {
50:         (, int256 answer, uint256 startedAt, , ) = sequencerUptimeFeed // @audit something about this from size lending
51:             .latestRoundData();
52: 
53:         // Answer == 0: Sequencer is up
54:         // Answer == 1: Sequencer is down
+55:         bool isSequencerUp = (answer == 0 && startedAt != 0);
-55:         bool isSequencerUp = answer == 0;
56:         if (!isSequencerUp) {
57:             revert SequencerDown();
58:         }
59:         console.logUint(startedAt);
60:         // Make sure the grace period has passed after the
61:         // sequencer is back up.
62:         uint256 timeSinceUp = block.timestamp - startedAt;
63:         if (timeSinceUp <= GRACE_PERIOD_TIME) {
64:             revert GracePeriodNotOver();
65:         }
66: 
67:         return true;
68:     }

```